[package]
name = "ruststack-auth"
description = "AWS Signature Version 2 and 4 request authentication for RustStack"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
hmac = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
chrono = { workspace = true }
percent-encoding = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
subtle = { workspace = true }
digest = { workspace = true }
sha1 = { workspace = true }
base64 = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
